
# Changing Frame Rates can change the quality of the video
# I.E. 30 fps = 1080p and 60 fps = 720p

# resolution = [854, 428]
resolution = [1280, 720]
# resolution = [1920, 1080]
# resolution = [2560, 1440]

website_ms_per_frame = 1000
seconds_per_frame = 16
jpg_quality = 30


# High Res 1080
# fps Quality Size 
# 30  95      700 kb
# 30  85      405 kb
# 30  70      275 kb
# 30  50      205 kb
# 30  30      160 kb
# 30  20      133 kb
# 30  10      100 kb

# Low Res 720
# fps Quality Size 
# 60  95      285 kb
# 60  85      175 kb
# 60  70      133 kb
# 60  50      93 kb
# 60  30      72 kb
# 60  20      60 kb
# 60  20      45 kb
